 export const per = [
    { id: 1, name: "ahmed", date: "5:00", img: "images.jpg" },
    { id: 2, name: "abd", date: "4:00", img: "images.jpg" },
    { id: 3, name: "ali", date: "5:00", img: "images.jpg" },
    { id: 4, name: "said", date: "3:00", img: "images.jpg" },
    { id: 5, name: "amr", date: "2:00", img: "images.jpg" },
    { id: 6, name: "demo", date: "1:00", img: "images.jpg" },
    { id: 7, name: "yahia", date: "9:00", img: "images.jpg" },
    { id: 8, name: "salem", date: "9:00", img: "images.jpg" },
    { id: 9, name: "maher", date: "9:00", img: "images.jpg" },
    { id: 10, name: "mazen", date: "9:00", img: "images.jpg" },
    { id: 11, name: "qusai", date: "9:00", img: "images.jpg" },
    { id: 12, name: "lama", date: "9:00", img: "images.jpg" },
    { id: 13, name: "sama", date: "9:00", img: "images.jpg" },
  ];